name: Fab Plugin Builds

on:
  push:
    tags:
      - "release/*"
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: [self-hosted, Windows, X64]
    defaults:
      run:
        shell: powershell
    env:
      PLUGIN_DIR: "Plugins/VMCLiveLink"
      ENGINE_ROOTS: 'C:\\Program Files\\Epic Games\\UE_5.4,C:\\Program Files\\Epic Games\\UE_5.5,C:\\Program Files\\Epic Games\\UE_5.6'
      ENGINE_VERSIONS: '5.4.0,5.5.0,5.6.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          
      - name: Set PowerShell Execution Policy
        run: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
        shell: powershell
        
      - name: Git LFS pull
        run: |
          git lfs install
          git lfs fetch --all
          git lfs pull

      - name: Ensure scripts exist
        run: |
          if (-not (Test-Path "scripts\build_fab.ps1")) {
            Write-Error "scripts/build_fab.ps1 not found. Commit the script to scripts/build_fab.ps1 or update the workflow path."
          }
          if (-not (Test-Path "scripts\add_copyright_headers.py")) {
            Write-Error "scripts/add_copyright_headers.py not found. Commit the script to scripts/add_copyright_headers.py or update the workflow path."
          }

      - name: Verify copyright headers
        run: |
          $PluginDir = $env:PLUGIN_DIR
          python "scripts\add_copyright_headers.py" $PluginDir --holder "Lifelike & Believable Animation Design, Inc." --verify

      - name: Build Fab packages
        run: |
          $PluginDir = $env:PLUGIN_DIR
          $OutputDir = "$(Resolve-Path .)\FabBuilds"
          New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null

          # Split env vars into arrays and trim any stray quotes/spaces
          $EngineRoots = ($env:ENGINE_ROOTS -split ",").ForEach({ $_.Trim(' ""') })
          $EngineVers  = ($env:ENGINE_VERSIONS -split ",").ForEach({ $_.Trim(' ""') })

          ./scripts/build_fab.ps1 -PluginDir $PluginDir -OutputDir $OutputDir -EngineRoots $EngineRoots -EngineVersions $EngineVers

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FabZips
          path: FabBuilds\*_Fab.zip
          if-no-files-found: error
